name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env.test
          echo DATABASE_URL="postgresql://postgres:password@localhost:5433" >> .env.test

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
